baseURL = "https://strongjz.github.io/aws-container-devsecops/"
languageCode = "en-us"
title = "AWS Container DevSecOps"
contentdir    = "content"
layoutdir     = "layouts"
publishdir    = "docs"
theme = "hugo-theme-learn"

[params]
  editURL = "https://github.com/strongjz/aws-container-devsecops"
  description = "AWS Container DevSecOps Workshop"
  author = "James Strong"
  themeVariant = "green"

[outputs]
home = [ "HTML", "RSS", "JSON"]
